# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(username: "Earn", email: "earn@earnmail.com", password: "flatiron")
user2 = User.create(username: "Paper Boi", email: "paperboi@mail.com",  password: "flatiron")
user3 = User.create(username: "Darius", email: "darius@chillmail.com",  password: "flatiron")
user4 = User.create(username: "Tracy", email: "tracy@mallmail.com", password: "flatiron")
user5 = User.create(username: "Van", email: "van@coolkid.com",  password: "flatiron")
user6 = User.create(username: "Clark County", email: "clark@county.com",  password: "flatiron")
user7 = User.create(username: "Lucas", email: "lucas@plane.com", password: "flatiron")
user8 = User.create(username: "Benny Hope", email: "benny@jackson.com",  password: "flatiron")
user9 = User.create(username: "Florida Man", email: "boogey@man.com" ,  password: "flatiron")
user10 = User.create(username: "Bibby", email: "best@barberever.com" ,  password: "flatiron")

picture1 = Picture.create(image_url: 'https://www.indiewire.com/wp-content/uploads/2016/08/atl_102_0465d.jpg', title: "Darius and Alfred", user_id: 1)
picture2 = Picture.create(image_url: 'https://www.billboard.com/files/media/atlanta-teddy-perkins-2018-billboard-1548.jpg', title: "Benny Hope", user_id: 8)
picture3 = Picture.create(image_url: 'https://extraimage.net/images/2018/04/14/880397d7c1e1a13f432102ab6252ce15.jpg', title: "Champagne Papi's House", user_id: 5)
picture4 = Picture.create(image_url: 'https://weliveentertainment.com/wp-content/uploads/2018/03/atlanta-bibby.jpg', title: "Bibby The Barber", user_id: 10)
picture5 = Picture.create(image_url: 'https://img.huffingtonpost.com/asset/5ac7c2102000002d00eb41a6.jpeg?ops=scalefit_970_noupscale', title: "Darius at Benny Hopes's House", user_id: 3)
picture6 = Picture.create(image_url: 'https://img.huffingtonpost.com/asset/5aa6de581f00001503169ea1.jpeg?ops=scalefit_970_noupscale', title: "Tracy visits The Mall", user_id: 4)
picture7 = Picture.create(image_url: 'https://movieplayer.net-cdn.it/images/2017/01/19/atlanta2.jpg', title: "Earn's Cookies", user_id: 1)
picture8 = Picture.create(image_url: 'https://img.huffingtonpost.com/asset/5af5cc2b2000004200b913af.jpeg?ops=1910_1000', title:"What Gold Gun?", user_id: 2)
picture9 = Picture.create(image_url: 'https://bloximages.chicago2.vip.townnews.com/pressofatlanticcity.com/content/tncms/assets/v3/editorial/5/1c/51cc919c-4dc0-55bc-b74f-af7c5ea296a9/5813ea0d4c75e.image.jpg?resize=1200%2C800', title: "Van and Earn", user_id: 6)
picture10 = Picture.create(image_url: 'https://images.spoilertv.com/cache/Atlanta/Season%202/Promotional%20Episode%20Photos/Episode%202.04%20-%20Helen/ATL_EP205_0863r_FULL.jpg', title: "Dude Seriously", user_id: 7)

robbin = Tag.create(name: "Robbin' Season")
awesome = Tag.create(name: "Awesome")
hilarious = Tag.create(name: "Hilarious")
wow = Tag.create(name: "Wow")
scary = Tag.create(name: "scary")
chillin = Tag.create(name: "Chillin")
drake = Tag.create(name: "Drake")
cookies = Tag.create(name: "Cookies")
darius = Tag.create(name: "Darius")
lmao = Tag.create(name: "LMAO")
piano = Tag.create(name: "Piano")
crazy = Tag.create(name: "Crazy")
cute = Tag.create(name: "Cute")

picture_tag1 = PictureTag.create(tag_id: 1, picture_id: 6)
picture_tag2 = PictureTag.create(tag_id: 2, picture_id: 7)
picture_tag3 = PictureTag.create(tag_id: 3, picture_id: 3)
picture_tag4 = PictureTag.create(tag_id: 4, picture_id: 4)
picture_tag5 = PictureTag.create(tag_id: 5, picture_id: 2)
picture_tag6 = PictureTag.create(tag_id: 6, picture_id: 1)
picture_tag7 = PictureTag.create(tag_id: 7, picture_id: 3)
picture_tag8 = PictureTag.create(tag_id: 8, picture_id: 7)
picture_tag9 = PictureTag.create(tag_id: 9, picture_id: 10)
picture_tag10 = PictureTag.create(tag_id: 10, picture_id: 5)
picture_tag11 = PictureTag.create(tag_id: 11, picture_id: 5)
picture_tag12 = PictureTag.create(tag_id: 12, picture_id: 6)
picture_tag13 = PictureTag.create(tag_id: 13, picture_id: 9)
#
# comment1 = Comment.create(content: "this is dope", user_id: 1, picture_id: 1)
# comment2 = Comment.create(content: "Benny did what?", user_id: 8, picture_id: 2)
# comment3 = Comment.create(content: "Where's Drake? Has anyone seen Drake?", user_id: 5, picture_id: 3)
# comment4 = Comment.create(content: "Bibby you actually gonna cut my hair?", user_id: 10, picture_id: 4)
# comment5 = Comment.create(content: "Yey I'm gonna get a free piano, wait what?", user_id: 3, picture_id: 5)
# comment6 = Comment.create(content: "I got vouchers man, we good", user_id: 4, picture_id: 6)
# comment7 = Comment.create(content: "These are what I call cookies!", user_id: 1, picture_id: 7)
# comment8 = Comment.create(content: "Dude who put this golden gun in my bag?", user_id: 2, picture_id: 8)
# comment9 = Comment.create(content: "So Lotties a genius! huh!", user_id: 6, picture_id: 9)
# comment10 = Comment.create(content: "what the hell is Fastnacht anyway?", user_id: 7, picture_id: 10)
